#! /bin/sh
killall -q sxkd
killall -q picom
killall -q dunst

eww kill

# autostart
#pgrep -x sxhkd > /dev/null || sxhd &
#picom &
# killall sxhkd dunst
sxhkd -c ~/.config/sxhkd/sxhkdrc &
picom &
# nitrogen --restore &
wal -i /mnt/A/pictures/wallpapers/1mHz44Z.jpg &
bash ~/.config/polybar/launch.sh --grayblocks &
clipmenud &
dunst &
eww open sidebar &
# kmonad ~/.config/kmonad/base.kbd &

# MPD start if no instance exists
[ ! -s ~/.config/mpd/pid ] && mpd &

# Get rid of cursor >:(
unclutter --start-hidden --timeout 1 &

# workspaces - 5 screens
bspc monitor HDMI-A-0 -d 1 2 3 4 5
bspc monitor HDMI-A-1 -d 6 7 8 9 10
# other GPU inputs
#bspc monitor DisplayPort-0 -d 1 2 3 4 5
#bspc monitor DisplayPort-1 -d 1 2 3 4 5

### Other Stuff
bspc config border_width 3
bspc config window_gap 8
bspc config split_ratio 0.6

# Eww Sidebar on monitor 1
# bspc config -m HDMI-A-0 left_monocle_padding 40
bspc config -m HDMI-A-0 left_padding 64

bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color "#327bd1"
bspc config urgent_border_color "#dd2727"

bspc config single_monocle true
bspc config presel_feedback true

bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config pointer_modifier shift
bspc config pointer_action1 resize_side
bspc config pointer_action3 resize_corner
bspc config swallow_first_click true

# check scratchpad already running
# bspc rule -a scratchpad sticky=on state=floating hidden=on
# [ "$(ps -x | grep -c 'scratchpad')" -eq "1" ] && st -c scratchpad -e ~/.config/bspwm/scratch &

### Rules
bspc rule -a Zathura state=tiled
bspc rule -a scpad sticky=on state=floating rectangle=800x400+1600+150
bspc rule -a mpdplayer sticky=on state=floating rectangle=600x600+50+150
bspc rule -a pavucontrol sticky=off state=floating rectangle=600x300+50+100

# Alert
# dunst
sleep 0.5
notify-send "Bspwm Loaded"
