local legend = require("keymaps.documentation")
local add_simple = legend.add_simple_to_legend
local add_regular = legend.add_to_legend

add_simple("J", "Global: Move 5 Rows Down")
add_simple("K", "Global: Move 5 Rows Up")
add_simple("0", "Global: Go to First Non-blank Character in Line")
add_simple("|", "Global: Enter Insert Mode at First Non-blank Character in Line")
add_regular("Alt+k", "Global: Move Current Line (N) or Selection (V) up", nil, nil, { "n", "v" })
add_regular("Alt+j", "Global: Move Current Line (N) or Selection (V) down", nil, nil, { "n", "v" })
add_regular("<", "Global: Outdent Current Line", nil, nil, { "n", "v" })
add_regular(">", "Global: Indent Current Line", nil, nil, { "n", "v" })
add_simple("<C-h> || <C-l>", "Global: Focus Window L/R")
add_simple("<C-j> || <C-k>", "Global: Focus Window U/D")
add_simple("<Leader>s{h/l}", "Global: [S]end Window to Most L/R position")
add_simple("<Leader>s{j/k}", "Global: [S]end Window to Most U/P position")
add_simple("<Leader>s<Space>", "Global: Swap Window With Neighbor")
add_simple("<Leader>f", "Global: [F]ocus Buffer (Use Bufnr)")
add_simple("Alt-h || Alt-l", "Global: Rotate Windows Clockwise/CClockwise")
add_simple("-", "Global: Open Window Switcher")
add_simple("RL || RH", "Global: [R]esize Window in L/R direction")
add_simple("RJ || RK", "Global: [R]esize Window in U/D direction")
add_simple("ta", "Global: [T]ab [A]dd (New Tab)")
add_simple("tc", "Global: [T]ab [C]lose")
add_simple("tl || th", "Global: [T]ab Next/Prev")
add_simple("tsl || tsh", "Global: [T]ab [S]end Next/Prev")
add_simple("<Leader>2", "Global: Show Vim Messges")
add_simple(",<Tab>", "Global: Clear Popups (Fix UI)")
add_simple("<Leader>cd", "Global: [C]hange Local [D]irectory (To Current Buffer)")
add_simple("Alt+Y", "Global: TODO - Global Yanker")
add_simple("F3", "Global: Run Checkhealth")

add_simple("<Space>c", "Global: MAKE [C]change in Word")
add_simple("<Space>d", "Global: MAKE [d]elete in Word")
add_simple("<Space>D", "Global: MAKE [D]elete in Line")
add_simple("<Space>Y", "Global: MAKE [Y]ank in Word")
add_simple("<Space>y", "Global: MAKE [y]ank in Line")
add_simple("<Space>m", "Global: MAKE [m]ark (in 'z')")
add_simple("<Space>b", "Global: MAKE Go to '[b]ook' mark ('z')")
add_simple("<Space>{j/k/l}", "Global: MAKE Cursor Bottom/Top/Center")
add_simple("<Space>wl", "Global: MAKE [w]indow Split Right")
add_simple("<Space>wh", "Global: MAKE [w]indow Split Left")
add_simple("<Space>wj", "Global: MAKE [w]indow Split Down")
add_simple("<Space>wk", "Global: MAKE [w]indow Split Up")
add_simple("<Space>n", "Global: MAKE Buffer Swap With Less Recent")
add_simple("<Space>p", "Global: MAKE Buffer Swap With More Recent")
add_simple("<Space>x", "Global: MAKE Current File E[x]ecutable")
add_simple("<Space>s", "Global: MAKE Search and Replace (Uses current word under cursor)")

return legend
